### ISSUE TITLE
Registration is no longer working

### ISSUE THREAD

**Issue by darko-mijic** [meteor-space/donations#16]
OrgRegistrationsController publishes Donations.OrgRegistrationRequested but there is no method in the api.

**Comment by DominikGuzei** [comment]
Strange, for me everything works correctly on latest `develop` – maybe you need to run mgp again?

**Comment by DominikGuzei** [comment]
and there should also be no method like that – it just publishes an event that the base class listens to :wink:

**Comment by darko-mijic** [comment]
you are right and it does work ;)
